### PR TITLE
feat(dialog): port v1 dialog plugin

### PR DESCRIPTION
**Pull request by bigopon**
# Pull Request

## 📖 Description

Port dialog plugin from v1, with the majority of the APIs kept as is, except renderer (simplified), and animation (removed - use `attaching`/`detaching` lifecycles).

Full documentation of this PR can be reviewed at https://github.com/aurelia/aurelia/tree/feat/dialog-plugin/docs/user-docs/plugins/dialog

### Dialog Service

Main API remains the same, except `component` should be a function that returns either a class, or a literal object, or a promise that resolves to either of those. Some examples:

```ts
dialogService.open({ component: () => MyDialog, template: 'my-template' })
dialogService.open({ component: () => MyDialog, template: document.createElement('my-template') })

// JSX to DOM
dialogService.open({ component: () => MyDialog, template: <my-template /> })

dialogService.open({ component: () => import('...'), template: () => fetch('my.server/dialog-view.html') })

// literal object as view model
dialogService.open({ component: () => ({ message: 'hello' }), template: `<input value.bind="message">` })
```

Any dialog service implementation should have the following interface:
```ts
interface IDialogService {
  readonly controllers: IDialogController[];

  open(settings?: IDialogSettings): DialogOpenPromise<DialogOpenResult>;

  closeAll(): Promise<IDialogController[]>;
}
```

A dialog controller implementation should follow the following interface:
```ts
interface IDialogController {
  readonly settings: Readonly<IDialogLoadedSettings>;
  /**
   * A promise that will be fulfilled once this dialog has been closed
   */
  readonly closed: Promise<DialogCloseResult>;

  ok(value?: unknown): Promise<DialogCloseResult<DialogDeactivationStatuses.Ok>>;
  cancel(value?: unknown): Promise<DialogCloseResult<DialogDeactivationStatuses.Cancel>>;
  error(value?: unknown): Promise<void>;
}
```

### Rendering extensions

In v1, different renderer can be registered to allow application to have different structures of the dialog dom. Though in v1, the renderers were taking quite a number of responsibilities: rendering, handling events, tracking controller, animation etc. In this implementation, the renderer is shrunk into a single purpose: render a object `IDialogDom` with the following interface:

```ts
interface IDialogDom extends IDisposable {
  readonly overlay: HTMLElement;
  readonly contentHost: HTMLElement;
}
```

The interface of the `IDialogRenderer`:
```ts
interface IDialogDomRenderer {
  render(dialogHost: Element, settings: IDialogLoadedSettings): IDialogDom;
}
```

### Activation

Activation hooks from v1 are supported, the hooks are:
- `canActivate(model)` (before controller `activate`)
- `activate(model)` (before controller `activate`)
- `canDeactivate` (before controller `deactivate`)
- `deactivate` (before controller `deactivate`)

### Animation

For animation, use `attaching` and `detaching` lifecycle if the intro & outro animations of a dialog should be awaited.

An example of animating a dialog on `attaching` and `detaching`, with the animation duration of 200 milliseconds:
```typescript

@inject(Element)
export class MyDialog {
  constructor(host: Element) {
    this.host = host;
  }

  attaching() {
    const animation = this.host.animate(
      [{ transform: 'translateY(0px)' }, { transform: 'translateY(-300px)' }],
      { duration: 200 },
    );
    return animation.finished;
  }

  detaching() {
    const animation = this.host.animate(
      [{ transform: 'translateY(-300px)' }, { transform: 'translateY(0)' }],
      { duration: 200 },
    );
    return animation.finished;
  }
}
```

Note that in the above animation example, we are using standard animation API `animate`: https://developer.mozilla.org/en-US/docs/Web/API/Element/animate

### CODE REVIEW

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=567344539626a7d206f1d2f58c78415407e769bd&branch=feat/dialog-plugin&commit=3ada28bf29c10c997a2132b32ab483cc1a387c59

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=d13dbf818ff557434f9cd13c71734320852e90cc&branch=feat/dialog-plugin&commit=7ca0502f8dd0fefb6f6e5452d6c7073cd72e390b

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=d13dbf818ff557434f9cd13c71734320852e90cc&branch=feat/dialog-plugin&commit=b3b184b5a57ef4b0c6daa3377d18ae32a0991b53

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=d13dbf818ff557434f9cd13c71734320852e90cc&branch=feat/dialog-plugin&commit=19ee1e630938ebd7d097ebfac4acf79c75b8d2be

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=ba7cb15fc8c07063d695500810071b57409b9500&branch=feat/dialog-plugin&commit=a4c801a011cd128d2ab5a56ab679e356df0f9a52

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=ba7cb15fc8c07063d695500810071b57409b9500&branch=feat/dialog-plugin&commit=acb707949186bd8060bcef5a305abb4d5283ab10

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=ba7cb15fc8c07063d695500810071b57409b9500&branch=feat/dialog-plugin&commit=36bbe0562fcec949d2135ed17c56e6c4640d9315

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=ba7cb15fc8c07063d695500810071b57409b9500&branch=feat/dialog-plugin&commit=9618ec87ba343bd681e9e733625330bb9b8e7e6f

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=ba7cb15fc8c07063d695500810071b57409b9500&branch=feat/dialog-plugin&commit=f7099ba88bc48daa6e7152cfdcc17c5b05aa9b4b

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=94a1eab25c0f37d53adb8813ac35ffa919135fba&branch=feat/dialog-plugin&commit=377ef22ad3c67cf72269c4a6cd2c325ddc74717b

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=94a1eab25c0f37d53adb8813ac35ffa919135fba&branch=feat/dialog-plugin&commit=729d4bb871611807ec10637699bc84c967e69817

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=b270d9d04843702d2d2b6771f4997337b0886273&branch=feat/dialog-plugin&commit=ebcba06d401e364829d56200a0747150c3f2e6b8

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=b270d9d04843702d2d2b6771f4997337b0886273&branch=feat/dialog-plugin&commit=ebcba06d401e364829d56200a0747150c3f2e6b8

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=a23dd29e78c0ddeda2fa053f09fabe813c33be9b&branch=feat/dialog-plugin&commit=653ef456bf2de5ea4150e081e7ec3d04eb54c87c

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=a23dd29e78c0ddeda2fa053f09fabe813c33be9b&branch=feat/dialog-plugin&commit=66e8b10b7871212b1457054456bdcc6473c81c67

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=a23dd29e78c0ddeda2fa053f09fabe813c33be9b&branch=feat/dialog-plugin&commit=6053a24c94a1e488af8881bea8b979bed45bf8b5

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=a23dd29e78c0ddeda2fa053f09fabe813c33be9b&branch=feat/dialog-plugin&commit=6053a24c94a1e488af8881bea8b979bed45bf8b5

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=c41e3907d9e7a8d5090cd255192d37d9bcea838e&branch=feat/dialog-plugin&commit=abbc137b085c810f1d732faa297fdbb562b0ae6e

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=c41e3907d9e7a8d5090cd255192d37d9bcea838e&branch=feat/dialog-plugin&commit=abbc137b085c810f1d732faa297fdbb562b0ae6e

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=e4b40498cab6dd9234066498f574b66acbb49ee6&branch=feat/dialog-plugin&commit=a017c9fb9a3ed69ea9d682cb916f6234b38ddcdf

**Comment by 3cp** [comment]
I like that you removed all the header/body/footer custom elements from au1 dialog.

**Comment by bigopon** [comment]
@3cp yes, not all apps need them so I prefer we start with something simple. I think we can always add a section to our doc for how to create them. My plan for the dialog examples doc:
- some common pattern like dialog/body/header/footer/attach-focus
- some common usage like a alert/confirm/prompt dialog system

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=2bc27711f7c8dcd82e26809c25ebb5a10bcae397&branch=feat/dialog-plugin&commit=cfe3b133a6c95505ccb164b178a3020d7581261c

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=2bc27711f7c8dcd82e26809c25ebb5a10bcae397&branch=feat/dialog-plugin&commit=4568d9fa27583021a3c4151aa78243578e1529f2

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=2bc27711f7c8dcd82e26809c25ebb5a10bcae397&branch=feat/dialog-plugin&commit=4cd0f4a9a561de04d2d384c512f5ffe13a508122

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=d893ca7eed388f57ddd46d2df0e54afddcaf2d8e&branch=feat/dialog-plugin&commit=9ece814ef4a5d6e04d9b96bf0264a70b3c4d380f

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=4a3fe2911a9ae13bb244f2603c7b6570af2c9d55&branch=feat/dialog-plugin&commit=53f95a43768dcda94116b2b69469fb0d0eb1ce29

**Comment by bigopon** [comment]
@fkleuver @Sayan751 @Vheissu I'll merge this for now, a few folks have been asking about it. If you are unhappy about some implementation, or doc, we can always change later.

**Pull request merged**
