### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by adriatic**
# Pull Request

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Actually, this one isn't a typo. We're spinning up a new realtime chat on Discord specifically as part of the Aurelia 2 alpha. So, this is an example of where the docs are a bit ahead of the alpha announcement.

**Comment by adriatic** [comment]
I will admit that I was concerned about this PR (A few lines above is a real reference to Discourse) and I had hard time believing that someone would make such mistake. 

Can I get access to Discord - if that is not ready for ordinary folks, I will ask questions and post comments in GitHub

**Comment by EisenbergEffect** [comment]
The link is in the main readme for this repo. But there's not much happening there yet. Almost nothing in the public channels now, since we haven't made any announcement.

**Comment by adriatic** [comment]
OK, I will wait when the Discord becomes ready. In the mean time my **[comment](https://github.com/aurelia/aurelia/issues/509#issuecomment-518916315)** summarizes what I think I need to get myself going with writing some basic Aurelia 2 apps.

**Comment by brandonseydel** [comment]
Take a look in https://github.com/aurelia/aurelia/tree/master/test there are all the major benchmarks and realworld implementation done in au2.  Also you can check my repo for a native material implemenation for au2.  I will commit those changes soon.  A lot of "bells and whistles" have came out of that development and reached main.

**Pull request closed without merging**
