### PR TITLE
chore: update (dev)Dependencies

### PR DESCRIPTION
**Pull request by BBosman**
# Pull Request

## 📖 Description

Update `mocha` to `^6.0.1`,  and the other (dev)Dependencies while at it.

### 🎫 Issues

n/a

## 👩‍💻 Reviewer Notes

With the exception of `mocha` only minor and patch releases.

The `mocha` breaking change is mostly about dropping old Node versions.

## 📑 Test Plan

Did some spot checking and will trust in CircleCI.

## ⏭ Next Steps

n/a

### CODE REVIEW

**Comment by fkleuver** [comment]
Thanks :) I really feel like we should get renovate to do this automatically for us though. Any chance you could look into that?

**Comment by BBosman** [comment]
@fkleuver Sure, but I don't think I have permissions to install the `renovate` bot into the repository.

Once it's there I can play around with the onboarding PR it generates.

**Comment by BBosman** [comment]
@EisenbergEffect Sent @aurelia a request through Renovate to enable the above.

**Comment by EisenbergEffect** [comment]
@BBosman Approved. You should be good to go.

**Pull request merged**
