### PR TITLE
chore(examples): remove outdated examples, add webpack-conventions example

### PR DESCRIPTION
**Pull request by 3cp**
Only two examples: jit-webpack-conventions-ts and jit-webpack-vanilla-ts.
There are few browserify setup in packages/__tests__/router/e2e I did not touch.

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37946-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37966-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by 3cp** [comment]
@fkleuver the CI is waiting for something. Where is the "required" jit-parcel-ts and jit-webpack-ts setup? Somewhere on our circleci account?

**Comment by fkleuver** [comment]
@3cp Might be a caching issue. The workflow itself is all green:

image

Is it ready as far as you're concerned? Then I'll just force merge it

**Comment by 3cp** [comment]
Yes.

**Pull request merged**
