### PR TITLE
refactor(au-compose): always create host for non custom element composition

### PR DESCRIPTION
**Pull request by bigopon**
## 📖 Description

Currently the `<au-compose/>` composition tries to be smart when composing non-custom element:
- if the `<au-compose/>` usage is not `containerless` (via `<au-compose containerless/>` usage): it'll use its own host element (`<au-compose/>` element) as the host for the composition
- if the `<au-compose/>` usage is a containerless: it'll use its comment markers as the comment markers for the composition

This has a few issues:
- unclear & hard to understand behavior, as questioned by #1806
- complicated implementation

This PR refactors the `<au-compose/>` composing behavior:
- `<au-compose/>` itself will always be containerless
- non custom element host element is always created, but will be replaced by a marker if there's no host element name specified
    - For example, the following template
    ```html
    <au-compose component.bind="{ a: 1 }" template="<div>hey</div>">
    ```
    will result in rendered composed html (ignore the `<au-compose/>` related own html):
    ```html
    <!--au-start--><div>hey</div><!--au-end-->
    ```
    This is often the desired behavior, but sometimes it's also necessary to have a wrapping element for regardless what the template for the composition is, imagine composing form fields wrapping in a field container:
    Usage:
    ```html
    <au-compose component.bind="{  name: firstName }" template="<input class='field-control' value.bind='name'>">
    ```
    Desirable output:
    ```html
    <div>
      <input class="field-control">
    </div>
    ```
    This can be achieved via `tag` binding on the `<au-compose>` element. `tag` is a new bindable property of the `<au-compose>` element and is used to specify what element to create in the non custom element composition. For the above example, we can do:
    ```html
    <au-compose
        component.bind="{  name: firstName }"
        tag="div"
        template="<input class='field-control' value.bind=name>">
    ```
    All the extra bindings on the `<au-compose/>` usage will also be transferred to this host element, which means we can do
    ```html
    <au-compose tag="div" class="field-container" template="...">
    ```
    to have the following composed html:
    ```html
    <div class="field-container">...
    ```

### CODE REVIEW

**Comment by bigopon** [comment]
cc @Sayan751 @fkleuver @ekzobrain

**Comment by ekzobrain** [comment]
@bigopon give me a couple of days, please. Need to dive in again.

**Comment by bigopon** [comment]
doc change is here https://github.com/aurelia/aurelia/pull/1906/files#diff-8cd6af03635c2537aa4b1ff7d67527c37afa3205f4e823d8c79620fe9cfcea54R62

**Comment by bigopon** [comment]
@ekzobrain no worries. I'll go ahead first, will accommodate any issues we discover

**Pull request merged**
