### PR TITLE
fix: bindable definitions

### PR DESCRIPTION
**Pull request by Sayan751**
# Pull Request

### 🎫 Issues

Closes the issue reported [here](https://discourse.aurelia.io/t/new-release-au-v2-beta-20/5491/4?u=sayan751).

### CODE REVIEW

**Comment by Sayan751** [comment]
@bigopon I am merging this. I can take care of any issues, you might notice, in a subsequent PR.

**Comment by 3cp** [comment]
Not sure if there are other decorators affected by this ts 5.5 ordering issue.

**Comment by 3cp** [comment]
Probably need some unit tests to make sure `@bindable` and `@bindable()` work with ts 5.5..

**Comment by Sayan751** [comment]
@3cp There are already some API checks in the same file. That contains all flavors of `@bindable`. That should provide sufficient safeguard.

**Pull request merged**
