### PR TITLE
chore(tests): add more replaceable tests

### PR DESCRIPTION
**Pull request by bigopon**
# Pull Request

## 📖 Description

More tricky usage of replaceable

### 🎫 Issues

N/A

## 👩‍💻 Reviewer Notes

N/A

## 📑 Test Plan

N/A

## ⏭ Next Steps

More tests

### CODE REVIEW

**Comment by bigopon** [comment]
@EisenbergEffect @fkleuver This is ready to go, though I'm not sure why irrelevant tests are failing.

**Comment by fkleuver** [comment]
@bigopon It's a known issue, they'll be fixed with my lifecycle PR. Thanks for adding tests and sorry for the late merge, I missed your ping for some reason and thought this was still WIP until I looked throught the PRs just now

**Comment by bigopon** [comment]
@fkleuver This also contains some missing passing tests, which should help contribute to overall robustness of our implementation.

**Comment by fkleuver** [comment]
@bigopon Nice. I'm seeing some new failures in browser stack tests for some reason. Could you merge master?

**Pull request merged**
