### PR TITLE
feat(capture-attrs): basic runtime infra for capturing attrs

### LINKED ISSUE #319: [Feature] Transparent Wrapper Components in Aurelia
# 🙋 Feature Request

One of the most exciting features in `Vue.js` is called **Transparent Wrapper Components**.
You can find some information from [here](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components).

When we were developing Aurelia-Toolbelt, we were faced with this problem a lot. For example, a new component has actually developed a base component such as **input**

I wrote [Aurelia-Toolbelt Float-Input](https://aurelia-toolbelt.github.io/#/bootstrap/float-input)

You can use this like

```html
<abt-float-input type='email' placeholder='email@example.com'>Email</abt-float-input>
```

Suppose I want to add maxlength="10" to this element.

```html
<abt-float-input type='email'  maxlength="10" placeholder='email@example.com'>Email</abt-float-input>
```

As you know `abt-float-input` is nothing more than an extended input element. so I want to transfer all dedicated attributes of an input HTML element to input element of the `float-input` template.

image

I think this is very very very useful for creating any UI component. We can rewrite all Aurelia-Toolbelt components with the benefit of HTML existing attributes.

## 🤔 Expected Behavior

I can use any dedicated attributes of HTML besides my new features/bindings/attributes.

## 😯 Current Behavior

I should implement all attributes one by one. 

## 💁 Possible Solution

I have not enough knowledge about how to add this feature. but @bigopon helps me about this in [here](https://discourse.aurelia.io/t/assign-all-new-attributes-to-specific-element-transparent-wrapper-components)

We want to create custom attributes eg `au-bind`. We can assign `au-bind` to target element inside a template when developing an element. after that, It should bind all attributes of a new custom element to the target element.

image

## 💻 Examples

I think the above sample is enough I wrote that with `Vue.js` in [here](https://jsfiddle.net/qLy47hj2/1/). I am not sure the best way for Aurelia.

Please consider this feature. It is very important and useful for using HTML features besides Aurelia capability to create complete and powerful UI toolkit especially when you want to wrap some frameworks and libraries.

### LINKED ISSUE #422: [Bug] Compose Should Transfer Attributes to Composed Elements
# 🐛 Bug Report

Any non-white-listed attribute that's placed on the `au-compose` element itself should be transplanted onto the actual composed element.

## 🤔 Expected Behavior

Given the following HTML:

```XML
<template repeat.for="space of spaces">
  <au-compose :subject="space" class="space-container ${space.isActive ? 'active' : ''}"></au-compose>
</template>
```

Assuming that the subject produces a `my-space` custom element and that `space.isActive === true`, at runtime we should see the following composed in the DOM:

```xml
<my-space class="space-container active"></my-space>
```

## 😯 Current Behavior

Currently, no attributes are transplanted onto the composed element. We would see the following in the DOM:

```xml
<my-space></my-space>
```

## 💁 Possible Solution

I haven't dug into the code to see what exactly is going on yet. It's either in the `au-compose` element code or in the `createElement` code. The `createElement` function should have the core capability of doing this so there's probably either a bug there or in how the `au-compose` element is collecting the initial bindings or passing them along.

## 🔦 Context

Due to the current issue, additional HTML elements have to be constructed around composed elements to handle the `class` scenario. This is workable but can create some issues with layout. However, beyond `class`, any attribute should work and if the custom element needs custom attribute bindings, this bug creates a block for the developer.

### LINKED ISSUE #497: au-compose should pass through bindings and content
# 🐛 Bug Report

When using the `au-compose` element, any bindings on `au-compose` should function as if they were actually declared on the composed element instead. Any content placed inside the `au-compose` start and end tags, should render as if it were placed in between the composed element's start and end tags.

## 🤔 Expected Behavior

Elements that are dynamically composed should function exactly as if they were statically declared inline, with their bindings and content HTML.

## 😯 Current Behavior

Currently, neither bindings nor content are passing through. The original implementation I did was a quick hack and the templating engine has changed significantly since it was done. So, we need to revisit this and get it working.

## 🔦 Context

Without this feature, the `au-compose` element is significantly reduced in power, since there's no way to get any contextual data into the composed element.

## 💻 Code Sample

We'd like to be able to write something like this:

```HTML
<au-compose subject.bind="myElement" some-prop.bind="foo">
  <div>Some content...</div>
</au-compose>
```

And have the runtime behave as if this were written:

```HTML
<my-element some-prop.bind="foo">
  <div>Some content...</div>
</my-element>
```

> Note: `my-element` is determined at runtime based on the value of `myElement`. The concrete element name is used here for example purposes.

### PR DESCRIPTION
**Pull request by bigopon**
# Pull Request

## 📖 Description

Define new config for custom element to be able to relay any non-bindable bindings put on its host for later use within its template.

### 🎫 Issues

Closes #422 
Closes #497
Closes #319 

Resolves https://discourse.aurelia.io/t/assign-all-new-attributes-to-specific-element-transparent-wrapper-components/1949

## 👩‍💻 Reviewer Notes

TBU

## 📑 Test Plan

TBU

## ⏭ Next Steps

Work out children/slot issues with `<compose/>`

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://29897-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://30191-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by bigopon** [comment]
For the following example:
```ts
@customElement({
  name: 'foo'
  captureAttrs: true,
})
export class Foo{}
```
```html
<foo class="hello" id="au" value.bind="barz"></foo>
```
should we capture `class`, `id` as well? or by default, only capture the attribute with bindings?

**Comment by fkleuver** [comment]
What about:

```ts
@customElement({
  name: 'foo'
  captureAttrs: AttrFilter.all, // capture `class`, `id`, etc
})
export class Foo{}
```

```ts
@customElement({
  name: 'foo'
  captureAttrs: AttrFilter.bindingCommands, // only capture bindings
})
export class Foo{}
```

```ts
@customElement({
  name: 'foo'
  captureAttrs: AttrFilter.plain, // only capture non-bindings
})
export class Foo{}
```

**Comment by bigopon** [comment]
That is nice looking config 👍

**Comment by bigopon** [comment]
@fkleuver So it will be like this:

```ts
@customElement({
  name: 'foo'
  captureAttrs: AttrFilter | string[]
})
export class Foo{}
```

**Comment by fkleuver** [comment]
@bigopon I meant this actually:

```ts
@customElement({
  name: 'foo'
  captureAttrs: AttrFilter | RegExp
})
export class Foo{}
```

It seems a bit simpler and more flexible to use a regexp for an api like this (one of the few exceptions I guess) but I don't feel strongly about it.

**Comment by bigopon** [comment]
I think string is more intuitive as a config, and Regexp isn't always welcomed. Let's go with `string[]`, we can always add Regexp later

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://30382-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by brandonseydel** [comment]
I like the capture attrs.  I wonder though if this should include an object for include/exclude explicit.

If i wanted every attribute except style we would need to exclude it.

```ts

type CaptureAttrDef = {
include: AttrFilter | string | string[],
exclude: AttrFilter | string | string[],
}

captureAttrs: {
include: AttrFilter.All,
exclude: 'style'
}
```

**Comment by bigopon** [comment]
I think exclude only has some meaning when it's used together with `AttrFilter.all` or a `RegExp`, for now, we don't have Regexp (yet) and `all`, well I'm not sure. Maybe it makes more sense than I thought. Could just do:
```ts
captureAttrs: {
  include: AttrFilter.All,
  exclude: ['style', 'class', 'id']
}
```

**Comment by fkleuver** [comment]
This is starting to feel a bit like bike shedding though. I'm inclined to say let's stick to just the enum until someone asks for more flexibility.

**Comment by EisenbergEffect** [comment]
As a quick FYI, for au-compose, we need the ability to transfer all attributes, both bound and unbound, to the composed element, with the exception of whatever bindables that au-compose defines for itself. e.g. subject

**Comment by fkleuver** [comment]
> until someone asks for more flexibility.

->

> with the exception of whatever bindables that au-compose defines

I suppose someone has asked for more flexibility 😄

**Comment by bigopon** [comment]
> Quick real use case: for au-compose, we need the ability to transfer all attributes, both bound and unbound, to the composed element, with the exception of whatever bindables that au-compose defines for itself. e.g. subject

Yes this was default behavior I wanted it to be, and I think it would be pretty confusing if not

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://30563-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://30885-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Pull request closed without merging**
