### PR TITLE
Add CustomAttribute.for api, and use weakmaps

### PR DESCRIPTION
**Pull request by fkleuver**
# Pull Request

## 📖 Description

This PR:
- Is a **BREAKING CHANGE** - `node.$au` and `node.$controller` no longer exist
- Removes any direct references from DOM nodes to controllers or controller lookups, instead storing those references in weakmaps via the metadata api
- Adds the `CustomAttribute.for` api to retrieve a custom attribute instance (by name) from a node
- Shortens `CustomElement.behaviorFor` to `CustomElement.for`
- Adds `DOM.getEffectiveParentNode` (to support `searchParents` but also as a general utility) which traverses upwards in an "aurelia-aware" manner, including looking for containerless hosts (by using previousSibling to look for `au-start` comments) and traversing out of shadow roots (by looking for controller.projector.host on nodes whose parent is `null` and whose type is `DocumentFragment`)
- Adds `name` and `searchParents` parameters to `CustomElement.for`. `name` only returns a controller when the backing definition/viewfactory's name matches the provided name. `searchParents` will traverse up to parent nodes (including containerless and shadow roots, see DOM.getEffectiveParentNode) to find the "closest" controller.
- Adds `controller.is` to check whether the resource definition's name, or viewFactory's name (in case of synthetic) matches the provided name. Used by `CustomElement.for(node, name)` signature to filter by custom element name

### 🎫 Issues

- Closes https://github.com/aurelia/aurelia/issues/758
- Potentially fixes a memory leak discovered by @brandonseydel 

## 👩‍💻 Reviewer Notes

See `custom-attribute.ts`, `custom-element.ts`, `renderer.ts` and `projectors.ts` for the relevant node-to-metadata changes.

## 📑 Test Plan

There were already a number of tests for both APIs. Those tests are updated accordingly.

## ⏭ Next Steps

N/A

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://35177-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by EisenbergEffect** [comment]
This looks like a nice set of improvements. The API is much better and more polished. Breaking change to make this better is ok, esp. at this point in time. Fixing things up is pretty easy for anyone that relied on the internals directly.

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://35224-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://35248-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://35287-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://35303-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
Replaced by https://github.com/aurelia/aurelia/pull/767

**Pull request closed without merging**
