### PR TITLE
chore: upgrade babel-jest and ts-jest to latest version

### PR DESCRIPTION
**Pull request by 3cp**

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://52203-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by 3cp** [comment]
Something is wrong, the chrome tests always fail timeout without real failure.

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://54246-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://55028-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by 3cp** [comment]
@fkleuver it looks ready.

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://55918-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
Sorry, I missed this. Thanks @3cp !

**Pull request merged**
