### PR TITLE
feat: parcel2 integration

### PR DESCRIPTION
**Pull request by 3cp**
Note parcel2 has no official unit tests example for plugin. We need to fill it up in future.

Locally tested. Pending incorporate into aurelia/new skeletons.

### CODE REVIEW

**Comment by 3cp** [comment]
The plugin name is changed from `@aurelia/plugin-parcel` to `@aurelia/parcel-transformer` to follow parcel2's naming rule: `@scope/parcel-transformer[-{name}]`.
https://parceljs.org/plugin-system/authoring-plugins/#naming

**Comment by bigopon** [comment]
Looks all good to me, let's go and see if it publishes dev version smoothly.

**Comment by 3cp** [comment]
None of the core packages published a dev version. Is that a manual process?

**Comment by bigopon** [comment]
@3cp the pipeline failed https://app.circleci.com/pipelines/github/aurelia/aurelia/9901/workflows/6e2ecb34-3857-43d7-980b-396f176bcc10/jobs/80407

I've just rerun it. Probably will need to upgrade the github file

**Comment by bigopon** [comment]
it succeeded, I'm not sure what's with that node engine & eslint. The dev version should be on npm now.

**Pull request merged**
