### PR TITLE
fix(compose): define an infra for passing through bindings

### LINKED ISSUE #319: [Feature] Transparent Wrapper Components in Aurelia
# 🙋 Feature Request

One of the most exciting features in `Vue.js` is called **Transparent Wrapper Components**.
You can find some information from [here](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components).

When we were developing Aurelia-Toolbelt, we were faced with this problem a lot. For example, a new component has actually developed a base component such as **input**

I wrote [Aurelia-Toolbelt Float-Input](https://aurelia-toolbelt.github.io/#/bootstrap/float-input)

You can use this like

```html
<abt-float-input type='email' placeholder='email@example.com'>Email</abt-float-input>
```

Suppose I want to add maxlength="10" to this element.

```html
<abt-float-input type='email'  maxlength="10" placeholder='email@example.com'>Email</abt-float-input>
```

As you know `abt-float-input` is nothing more than an extended input element. so I want to transfer all dedicated attributes of an input HTML element to input element of the `float-input` template.

image

I think this is very very very useful for creating any UI component. We can rewrite all Aurelia-Toolbelt components with the benefit of HTML existing attributes.

## 🤔 Expected Behavior

I can use any dedicated attributes of HTML besides my new features/bindings/attributes.

## 😯 Current Behavior

I should implement all attributes one by one. 

## 💁 Possible Solution

I have not enough knowledge about how to add this feature. but @bigopon helps me about this in [here](https://discourse.aurelia.io/t/assign-all-new-attributes-to-specific-element-transparent-wrapper-components)

We want to create custom attributes eg `au-bind`. We can assign `au-bind` to target element inside a template when developing an element. after that, It should bind all attributes of a new custom element to the target element.

image

## 💻 Examples

I think the above sample is enough I wrote that with `Vue.js` in [here](https://jsfiddle.net/qLy47hj2/1/). I am not sure the best way for Aurelia.

Please consider this feature. It is very important and useful for using HTML features besides Aurelia capability to create complete and powerful UI toolkit especially when you want to wrap some frameworks and libraries.

### LINKED ISSUE #422: [Bug] Compose Should Transfer Attributes to Composed Elements
# 🐛 Bug Report

Any non-white-listed attribute that's placed on the `au-compose` element itself should be transplanted onto the actual composed element.

## 🤔 Expected Behavior

Given the following HTML:

```XML
<template repeat.for="space of spaces">
  <au-compose :subject="space" class="space-container ${space.isActive ? 'active' : ''}"></au-compose>
</template>
```

Assuming that the subject produces a `my-space` custom element and that `space.isActive === true`, at runtime we should see the following composed in the DOM:

```xml
<my-space class="space-container active"></my-space>
```

## 😯 Current Behavior

Currently, no attributes are transplanted onto the composed element. We would see the following in the DOM:

```xml
<my-space></my-space>
```

## 💁 Possible Solution

I haven't dug into the code to see what exactly is going on yet. It's either in the `au-compose` element code or in the `createElement` code. The `createElement` function should have the core capability of doing this so there's probably either a bug there or in how the `au-compose` element is collecting the initial bindings or passing them along.

## 🔦 Context

Due to the current issue, additional HTML elements have to be constructed around composed elements to handle the `class` scenario. This is workable but can create some issues with layout. However, beyond `class`, any attribute should work and if the custom element needs custom attribute bindings, this bug creates a block for the developer.

### LINKED ISSUE #497: au-compose should pass through bindings and content
# 🐛 Bug Report

When using the `au-compose` element, any bindings on `au-compose` should function as if they were actually declared on the composed element instead. Any content placed inside the `au-compose` start and end tags, should render as if it were placed in between the composed element's start and end tags.

## 🤔 Expected Behavior

Elements that are dynamically composed should function exactly as if they were statically declared inline, with their bindings and content HTML.

## 😯 Current Behavior

Currently, neither bindings nor content are passing through. The original implementation I did was a quick hack and the templating engine has changed significantly since it was done. So, we need to revisit this and get it working.

## 🔦 Context

Without this feature, the `au-compose` element is significantly reduced in power, since there's no way to get any contextual data into the composed element.

## 💻 Code Sample

We'd like to be able to write something like this:

```HTML
<au-compose subject.bind="myElement" some-prop.bind="foo">
  <div>Some content...</div>
</au-compose>
```

And have the runtime behave as if this were written:

```HTML
<my-element some-prop.bind="foo">
  <div>Some content...</div>
</my-element>
```

> Note: `my-element` is determined at runtime based on the value of `myElement`. The concrete element name is used here for example purposes.

### PR DESCRIPTION
**Pull request by bigopon**
# Pull Request

## 📖 Description

Define new config for custom element to be able to relay any non-bindable bindings put on its host for later use within its template.

### 🎫 Issues

Closes #422 
Closes #497
Closes #319 

Resolves https://discourse.aurelia.io/t/assign-all-new-attributes-to-specific-element-transparent-wrapper-components/1949

## 👩‍💻 Reviewer Notes

TBU

## 📑 Test Plan

TBU

## ⏭ Next Steps

Work out children/slot issues with `<compose/>`

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28270-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by EisenbergEffect** [comment]
Thanks for kicking this off @bigopon . I'm thinking that we may need two ways to use this:

* Designate an element within the template to specifically relay commands to.
* Capture the commands and dynamically apply them as needed (au-compose)

Do you think we can accomplish this with the same mechanism?

**Comment by bigopon** [comment]
@EisenbergEffect yes, those two ways of using it you mentioned is the reason why i went with this approach.

The first way is achievable via a custom attribute:
```ts
@customAttribute('relay-target')
export class RelayTarget {
  constructor(
    @IHydrateElementInstruction private readonly elementInstruction
    @INode private readonly element,
    @IRenderingEngine private readonly renderingEngine
  ) {
    renderingEngine.render(elementInstruction.instructions, element)
  }
}
```
Usage:
```html
<template>
  <input relay-target >
</template>
```

The second usage is the `<compose/>` element

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28468-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28548-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
@bigopon Is this the same issue as https://github.com/aurelia/aurelia/pull/668 or is this different?

**Comment by bigopon** [comment]
Yes, its the same, but older. We dont need to keep this

**Pull request closed without merging**
