### PR TITLE
refactor(plugin-conventions): simplify usage of html only element

### PR DESCRIPTION
**Pull request by 3cp**
# Pull Request

## 📖 Description

As Rob suggested, simplified HTML only element by implementing `register(container)` method in html module.

## 📑 Test Plan

Passed manually tested in app.

## ⏭ Next Steps

Need to update makes skeleton after this release.

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://26969-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by 3cp** [comment]
@EisenbergEffect question, do we want to support IE10 or below? If so, I need to replace `const` and `let` with `var` in compiled html code.

In all our default bundlers setup, html only goes through conventions plugin, not ts/babel. All bundlers understand esm code (we generated for html), so there is no problem.

IE11 and all other browsers support `const` and `let`.

**Comment by brandonseydel** [comment]
@3cp I would vote not.  Throughout all my consulting hours through various major companies they all either have IE11 or the ability to go to it and haven't.  Let's see what others think.

**Comment by EisenbergEffect** [comment]
@3cp I think we can leave it as is. If we get someone who makes the request later on, we could even add an option for that.

**Comment by EisenbergEffect** [comment]
This looks good. I'm going to merge. Glad it was a pretty easy to make the change. Not sure why I didn't think of this the first time.

**Comment by EisenbergEffect** [comment]
Note I may hold to merge this until later today so I don't break someone who may be in the process of installing deps this morning. I don't want them to get my old code with the new webpack plugin (they are on dev releases). But, I will get this in shortly.

**Pull request merged**
