### PR TITLE
docs(getting-started): Fix wrong filename in example.

### PR DESCRIPTION
**Pull request by danfma**
- The documentation says the user to create a new file called
`register`, but it imports it as `registry`.

# Pull Request

## 📖 Description

It fix a simple typo in the documentation.

### 🎫 Issues

None

## 👩‍💻 Reviewer Notes

None

## 📑 Test Plan

1. Generate the user documentation;
2. Go to the "Getting Started" > "Building Components";
3. Go to the "Component Registration" section;
4. Verify if the filename in the example is named "registry.ts".

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Good catch @danfma FYI For future docs fixes, don't feel obligated to fill out the test plan. We've got a general PR template, which is probably a bit overkill in some scenarios.

**Comment by EisenbergEffect** [comment]
Thanks for the fix @danfma !

**Comment by danfma** [comment]
@EisenbergEffect I'm reading the complete documentation in my free time, to see what has changed, and to try it in a pet project here. Once I got other issues, I will send to you, guys!

This new version looks great!

**Comment by EisenbergEffect** [comment]
Most of it is still placeholders. We're slowly migrating, reorganizing, and updating content. So, you might finish reading all of it pretty soon 🤣

**Pull request merged**
