### PR TITLE
chore: fix devDeps

### PR DESCRIPTION
**Pull request by BBosman**
# Pull Request

## 📖 Description

There are some devDependencies marked as dependencies and dependencies marked as devDependencies in the various `package.json` files. I think this mismatch is confusing `renovate`, resulting in PR's that fail the build.

## 👩‍💻 Reviewer Notes

Just `package.json` shuffling and updates, and corresponding fresh `package-lock.json` files.

I also had to pin `karma`, as `4.2.0` apparently has an unexpected breaking change from `4.1.0`, as it fails our CircleCI build.
And I also had to pin `mocha`, as `6.2.0` apparently also has an unexpected breaking change from `6.1.4`, as it also fails our CircleCI build.

## 📑 Test Plan

CircleCI

## ⏭ Next Steps

- See if `renovate` plays nice from now on.
- Investigate the unexpected `karma` and `mocha` breakage.

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://22011-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://22017-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://22029-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://22036-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://22050-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://22056-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
Excellent, big big thanks for taking care of this. Renovate was starting to get on my nerves :)
I wasn't even aware that some deps had slipped in as dev deps.

@Sayan751 @3cp please take note of what's changed in this PR as some of these deps were added by you.

**Pull request merged**
