### PR TITLE
feat(plugin-conventions): support customized element name in customElement

### LINKED ISSUE #810: Custom element with custom name
# Issue
When I use the "customElement" decorator and assign it a custom name, I am not able to load the item.

## 🤔 Expected Behavior
Use a custom element with custom name

## 😯 Current Behavior
When I use a custom element with the naming convention it works great. But when I want to use a custom name, neither with the custom name nor with convection,not load...

## 💻 Code Sample

demo.html
```html
<div>demo text</div>
```

demo.ts
```ts
import { customElement } from "aurelia";

@customElement('demo-custom')
export class Demo {
}
```

my-app.html
```html
<require from="demo"></require>
<div class="message">${message}</div>
<demo-custom></demo-custom>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | dev
| Language         | Spanish
| Browser          | Edge Chromium
| Bundler          | Webpack
| Operating System | Windows
| NPM/Node/Yarn    | Yarn

### PR DESCRIPTION
**Pull request by 3cp**
When there is a paired html file, rewrite `@customElement('name')` into `@customElement({ ...__au2ViewDef, name: 'lorem' })`.
When there is no paired html file, leave original decorator unchanged. The default behaviour in Aurelia 2 is like noView in Aurelia 1, but with a customized element name.

closes #810

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://43904-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by bigopon** [comment]
We can have this first and the full independent decorator follow later. It looks good to me, and pretty high value/effort ratio 😬

**Comment by 3cp** [comment]
> pretty high value/effort ratio

It is what you can expect from a Perl trained programmer, not necessarily a good sign. 😁

**Comment by 3cp** [comment]
Some strange error on unit_test_chrome, pls help  to rerun it @fkleuver .

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://43918-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
@3cp Done, all seems to pass now. Is this ready as far as you're concerned?

**Comment by 3cp** [comment]
Thx! Yes, that's the only part.

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://43993-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Pull request merged**
