### PR TITLE
browserstack

### PR DESCRIPTION
**Pull request by fkleuver**

### CODE REVIEW

**Comment by AureliaEffect** [comment]
This pull request **fixes 1 alert** when merging faace64f5d2168e14b4ff8dcefa3f72fb3562621 into 76d1aa3af248c435dd6e895a1758f7cf06d07cf4 - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-3964bff3f67f89bb9a4e212ed12317aa07f15399)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
This pull request **fixes 1 alert** when merging 384e9de083c8787d8d7ecd94db4cf77b64697402 into 76d1aa3af248c435dd6e895a1758f7cf06d07cf4 - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-8ba1bf48c8093477fbd8ff88797df9a461157498)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
This pull request **fixes 1 alert** when merging 4fb006b5d9434773e1839a58c47990e9dab4a40b into 76d1aa3af248c435dd6e895a1758f7cf06d07cf4 - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-4b525823ede94446b02f550cbd9957129aaf81ae)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
This pull request **fixes 1 alert** when merging 02549606cfa68b6f0e6fb22b131d0764bd826ab3 into cccab1f9c2df8d18a117b52e1d5322a165fab2bd - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-e7ad01ae62eae340be43f3936b970e668824f200)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
This pull request **fixes 1 alert** when merging 5520c13b018f78e0cef6b23c33bdad4f1f31a98f into cccab1f9c2df8d18a117b52e1d5322a165fab2bd - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-79acb3fb05a5297c6b4b09af8783e7856f611a20)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
This pull request **fixes 1 alert** when merging 642f7ac998d25147db443e1ceba3b1517bed8bbe into cccab1f9c2df8d18a117b52e1d5322a165fab2bd - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-b6c65b95969e9ccaeff414307ef149eb7f834b14)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
This pull request **fixes 1 alert** when merging b8ad510d66ca224648fb66b09adf3d63010430da into cccab1f9c2df8d18a117b52e1d5322a165fab2bd - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-d264bbf24618bbe3da7acef05b4b145779a1cc12)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
This pull request **fixes 1 alert** when merging fe88305781277ac6d5fcaa74fe8190e4a3c84927 into cccab1f9c2df8d18a117b52e1d5322a165fab2bd - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-5b128b440619981187f53ee1249ba71edf8819a2)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by fkleuver** [comment]
test

**Comment by fkleuver** [comment]
Allure Report: https://2360-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/e2e/allure-report/index.html

**Comment by AureliaEffect** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 067e52e88765a222481e8da28ea3d0bdd2e94ef9 into cccab1f9c2df8d18a117b52e1d5322a165fab2bd - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-8f81d99af04509aea15ee0cf0f8e700ef69c5ae5)

**new alerts:**

* 1 for Unused variable, import, function or class

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging c074af2cced4aed42b391810147e48fff1d95e44 into cccab1f9c2df8d18a117b52e1d5322a165fab2bd - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-bd7270ae57014b5b982847c81a9a0e06937c8ada)

**new alerts:**

* 1 for Unused variable, import, function or class

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 194dbb24197d8cd448026fbe1e17c28c572d5d66 into cccab1f9c2df8d18a117b52e1d5322a165fab2bd - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-589496951b542ed6b7a3171d44b409f585e4a13a)

**new alerts:**

* 1 for Unused variable, import, function or class

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by fkleuver** [comment]
@EisenbergEffect  good to go! The only thing left to do (for you) is change the `GITHUB_TOKEN` in the circleci env variable to the AureliaEffect account. Currenly it's my token in there :P (previous comment was posted by circleci)

**Pull request merged**
