### PR TITLE
Lifecycle hooks improvements

### PR DESCRIPTION
**Pull request by fkleuver**
# Pull Request

## 📖 Description

This PR will address 3 main topics:
### 1. Rename the lifecycle hooks from `-ing`/`-ed` to `before-`/`after-`. So:
  - `binding` -> `beforeBind`
  - `bound` -> `afterBind`
  - `attaching` -> `beforeAttach`
  - `attached` -> `afterAttach`
  - `detaching` -> `beforeDetach`
  - `detached` -> `afterDetach`
  - `unbinding` -> `beforeUnbind`
  - `unbound` -> `afterUnbind`
  This should hopefully make the concepts more intuitive and easier to understand for people new to them.
### 2. Improve the `render` lifecycle.
  The plan is to simplify the api contract of `render` such that the returned value matches the type that can be passed into the `subject` binding of `au-compose`, so any of:
  - IViewFactory
  - IController (a view essentially)
  - RenderPlan (something that can lazily produce definitions, views, templates or view factories)
  - Constructable (a custom element class)
  - CustomElementDefinition (partial, like `@customElement` decorator input, or pre-compiled)
  - A html string or DOM node (to be compiled by the JIT)
  - A promise returning any of the above (might scrap this bit though, depends on viability and perf impact)
  Also, rename `render` to ~~`compile`~~`create`, and add `beforeCompile` and `afterCompile` to match the semantics of the bind and attach hooks in terms of invocation order.
### ~~3. Add 4 additional hooks to support animation use cases.~~ (delayed)
  - `beforeChildrenAttach` (need better name, probably) -> will have the behavior of the current `attaching` hook
  - `afterChildrenAttach` -> will have the behavior of the current `attached` hook
  - `beforeChildrenDetach` -> will have the behavior of the current `detaching` hook
  - `afterChildrenDetach` -> will have the behavior of the current `detached` hook
  The semantics of `beforeAttach`, `afterAttach`, `beforeDetach` and `afterDetach` will be changed to happen immediately before and after mounting/unmounting, respectively, and will support returning promises which will delay the appropriate operation (for animating, primarily).
  More in-depth explanation with examples will follow as this will be the last of the 3 that I'll be working on, and it needs some experimentation before the final api can be finalized.

## ⏭ Next Steps

- Finish with the 3rd point
- Summarize the additional changes made in this PR related to `IRenderContext`, `IController` and the compile hooks
- Implement transfer-attrs and processContent

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I'd recommend against the promise possibility for the new compile hooks for now. I'd be concerned that might balloon complexity and cause some perf issues.

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37169-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37177-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37411-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37624-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37709-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37723-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37746-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://37972-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Pull request merged**
