### PR TITLE
fix(jest): fix jest v27 exports

### PR DESCRIPTION
**Pull request by 3cp**

### CODE REVIEW

**Comment by bigopon** [comment]
Interesting, why didn't we see it fail before. Though it can still manifest in newer PR.
Thanks @3cp

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=89adf8f6a5ee5b8809620e89afc19785c55010cc&branch=fix-jestv27-exports&commit=520ab8efc69ef76b6d56daa2ac0eaa1b5f6f1fc2

**Comment by 3cp** [comment]
It did not fail because we have no test setup for jest. We got only the unit tests for the functions.

**Comment by 3cp** [comment]
I am also running into issue of the latest ts-jest.
It now complains about cannot find source file for my-app.html.ts which doesn't exist but synthesised at testing time.
Only babel-jest works fine in jest v27 for now.

**Pull request merged**
