### PR TITLE
[WIP]: Routing Documentation

### PR DESCRIPTION
**Pull request by Vheissu**
A work in progress for routing docs.

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://48991-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
@Vheissu Why was this closed?

**Comment by Vheissu** [comment]
@fkleuver Because these changes ended up being committed via the GitBook interface, which rendered this PR irrelevant and now outdated.

**Comment by fkleuver** [comment]
Alright, thanks!

**Pull request closed without merging**
