### PR TITLE
Another simple (but funny) typo

### PR DESCRIPTION
**Pull request by adriatic**
# Pull Request

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks @adriatic Would you mind actually deleting the typo though?

**Comment by adriatic** [comment]
It's not that I am lazy - I am rather walking gingerly, looking for boundaries I should not cross :-)

**Comment by EisenbergEffect** [comment]
It's definitely ok to correct a typo 😄 

One thing I will say is that all of this documentation is very preliminary. It's nowhere near ready for most people to read. You may be the first person to look at any of this. Even our technical writer hasn't started working on it yet. I wanted to get a few more things ready before I put him to work. So, you're likely to see pretty big improvements in the existing content as well as lots of new content over the next few months.

One other note about the state of the content, many documents have just fragments in them and no context at all. This is because I'm still in the middle of aggregating our old docs, our old wiki, etc. and then re-organizing it into the new docs. The first stage of that is me just "dumping" bits and pieces into the article where I think they will go, without necessarily stringing the fragments together or writing any sort of intro yet.

**Comment by adriatic** [comment]
Being allowed to fix a typo is an obvious freedom for anyone that likes Aurelia. Let me also comment your text
> One thing I will say is that all of this documentation is very preliminary. It's nowhere near ready for most people to read.

I am not going to imply how you are "fishing for compliments", but I will say that 

- you selling yourself short. Regardless of much effort was put in this set of documents, the fact remains that they are phenomenal (relatively to old ones as well as absolutely). 

- my role is a lot more important than pointing out the typos - I have a fresh (and critical) mind that gives me the opportunity to point out where author's thoughts writing the docs have a break of continuity (because someone called to have dinner, or any other interrupt). I also want to point out at places where the example code is not "bidirectionally related" or simply incomplete. This is the consequence of the fact that anyone on your team member simply "interpolates" the missing information without even being aware of that.

Here is a good example (which I will state as my next issue) is missing the context in https://github.com/aurelia/aurelia/blob/master/docs/user-docs/6.%20community-contributions/4.%20building-and-testing-aurelia.md:

image

Interestingly enough, while I created this screenshot, I wanted to see what is Chris Cuomo talking about. Returning back, I note that you "sensed" my intent and did:

image

Good night and I realize that you can spent your time better than reading this.

**Comment by adriatic** [comment]
Why is it that this PR fails - is it because I did not change the typo (but rather pointed to it). 

At the time I created this PR I was not aware that it is OK to fix the typos, so when Rob told me to do that, I got stuck in the dilemma:

- can I edit a PR and resubmit it?
- if not, should I delete it and submit a new one instead?

These questions should be taken in the context of Aurelia development rules behaviour.

**Comment by EisenbergEffect** [comment]
The e2e tests are failing, which has nothing to do with your PR. Simply adding commits to the current PR, as you have done, is the proper way to respond to feedback on your PR. Merging... Congrats on your first contribution to Aurelia 2!

**Pull request merged**
