### PR TITLE
fix: disabled template controllers on local template surrogate

### PR DESCRIPTION
**Pull request by Sayan751**
# Pull Request

### CODE REVIEW

**Review by bigopon — APPROVED** [review]

**Comment by bigopon** [comment]
Lgtm, we could also pack the fix for surrogate instruction on local template by using the template element, instead of putting its content inside a `div`

**Comment by bigopon** [comment]
Sorry hit enter a bit early. I meant to say we should also fix the surrogate, either packing it in this PR, or another one. Both good to me

**Comment by Sayan751** [comment]
@bigopon 

>fix the surrogate

Do you mean if there are TCs on surrogate then put those attributes on a new templates that wraps the main content? Or do you mean the introduction of `<host>` element?

**Comment by bigopon** [comment]
It's already fixed with this
image

I was focusing on the changes in the tests and missed this 👍

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://58193-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://58379-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://58610-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://58710-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Pull request merged**
