### PR TITLE
Strict properties

### PR DESCRIPTION
**Pull request by fkleuver**
# Pull Request

## 📖 Description

This PR is an initial step in preparation for turning on the tsconfig.json options `strictPropertyInitialization` and `strictNullChecks` (the latter must be turned on in conjunction with the former).

Principles I applied:
1. No constructor short-hands; all properties are declared on class level (not required by strict property rule)
2. No declaration short-hands; properties are exclusively assigned inside the constructor (not required by strict property rule)
3. All properties are assigned a value during construction (required by strict property rule)
4. Similar properties on similar classes are declared and assigned in the same order as much as possible (not required by strict property rule)
5. Properties that are assigned conditionally and are difficult to keep in the same order per instance of the same class, are assigned a default value eagerly

I added 1. and 2. for consistency and improved debugging experience. It also makes properties easier to document and gives better (sense of) control over the order of assignment. It makes the code look more verbose, but the transpiled JS should be unaffected by this duplication because property declarations are removed anyway.

Point 4. reduces the learning curve when trying to understand multiple similar classes.
Point 5. is in many cases a minor perf improvement for the browser JIT because fewer variations of hidden classes need to be generated

Apart from that, this PR is also just meant as a motivating example for how to approach the rather large effort of enabling strict property initialization, to get the ball rolling, and perhaps to get the discussion going as well (I'm curious what @timfish thinks about this approach)

### 🎫 Issues

Related: https://github.com/aurelia/aurelia/issues/254

## 👩‍💻 Reviewer Notes

I went over all classes in the kernel and in the jit. No functional changes apart from property assignment order.
Pinging @timfish and @BBosman to glance over as well, since they brought this topic to the foreground from the tsconfig / tslint perspectives, respectively.

## 📑 Test Plan

If all CI checks pass, it should be good

## ⏭ Next Steps

The AST, all `IBinding` implementations and binding-resources (most of binding, really) seem like good next candidates since they're quite stable. If @timfish or @BBosman is interested in helping out that would be great. 

The observers have somewhat non-obvious interplay with typings and properties (my bad), and I think it's better if I take a look at that myself, but any ideas are of course welcome.

### CODE REVIEW

**Comment by BBosman** [comment]
I like what I'm seeing and I'm willing to give it a try on the AST.

There are a few instances where it isn't obvious what the default value should be, like:
```ts
public connect: IExpression['connect'];
```

What would you suggest as default value in this case?

**Comment by fkleuver** [comment]
Whenever there is a method signature declared on a property and it is not assigned in the constructor, 99% chance I've assigned `PLATFORM.noop` on the prototype somewhere down below in the same file. I'm doing this in various observers as well.

The motivation there is performance and library size. It's less code to assign the same function to the prototype, and it's more performance to reuse the same function multiple times. However, the latter is in theory and I'm not sure if there's actually much tangible gain to it in practice.

The problem with directly assigning `PLATFORM.noop` in the instance is that you then get a function per instance instead of one shared across all instances of a prototype, which leads to more properties defined and thus a higher memory usage. Again, it's incredibly small, so perhaps not worth it.

Perhaps a regular empty function with only a `return;` statement is the way to go.

**Comment by EisenbergEffect** [comment]
@fkleuver Recent merged require conflict resolution on this PR.

**Comment by fkleuver** [comment]
@EisenbergEffect fixed

**Comment by EisenbergEffect** [comment]
I'm down with this approach. While certain things are slightly less convenient, it provides greater clarity and consistency which I think are crucial, esp. when some of this can affect perf in hot code paths (something we always have to be sensitive of in a framework). @fkleuver Ready for me to merge this?

**Comment by fkleuver** [comment]
Yep ready

**Pull request merged**
