### PR TITLE
refactor(router): remove internal strings and scope class

### PR DESCRIPTION
**Pull request by jwx**
# Pull Request

## 📖 Description

This PR 
- makes router use `ViewportInstruction` everywhere (where it counts) internally
- makes `goto` the command to go to (used for almost everything)
- implements component instance as possible component in `NavigationInstruction`
- adds stateful history and configuration for it
- improves component clean up
- removes the `Scope` class (and moves necessary functionality into `Viewport`)
- makes viewports "hierarchy aware"
- awaits core regarding lifecycle actions such as attach
- reactivates several old deactivated tests
- generally cleans up code

It contains a BREAKING CHANGE for 2nd and 3rd parameters to `goto` as well as removes the `replace` method.

### 🎫 Issues

Related to https://github.com/aurelia/aurelia/issues/307, https://github.com/aurelia/aurelia/issues/369 and https://github.com/aurelia/aurelia/issues/367. 

## 👩‍💻 Reviewer Notes

Ignore everything in `packages/router/test/e2e/**` since they are just my own test applications while working.

## 📑 Test Plan

- Make sure existing tests pass.

## ⏭ Next Steps

- Fix `realworld`
- Fix proper sync/async for lifecycle hooks
- Add tests for the new au-nav options
- Add tests for the before navigation guard
- Finish navigation skeleton
- Finish scoped viewports review
- Add tests covering scoped viewports
- Review controller parent implementation
- Review the extension points

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28172-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28175-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28184-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28574-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
@jwx I have started taking a look at this PR. Code is looking better in a number of places which is nice.
Your description sounds good, there's one thing that confuses me a bit. How exactly is a viewport "hierarchy aware" now? Or are you still working on that?

**Comment by jwx** [comment]
@fkleuver Before this refactor, the `Viewport` wasn't aware of parent or children (hierarchy). Instead it had a `Scope` that knew that hierarchy. But `Scope` was from the beginning a (probably) temporary thing intended to go away. Now that it have, some of its responsibilities have been moved into `Viewport`.

**Comment by fkleuver** [comment]
@jwx Via which properties is it hierarchy aware?

**Comment by jwx** [comment]
@fkleuver Umm, `children` and `parent`.

**Comment by fkleuver** [comment]
doh :)

**Comment by bigopon** [comment]
Will the new hydration context able to help with anything?

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://29299-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Pull request merged**
