### PR TITLE
feat(route): add a way to access the current route

### PR DESCRIPTION
**Pull request by brandonseydel**
# Pull Request

### CODE REVIEW

**Comment by dtaalbers** [comment]
Any change we can get this added and merged? 😄

**Comment by brandonseydel** [comment]
@bigopon what can we do to move this forward?

**Comment by bigopon** [comment]
@brandonseydel I thought it's still a WIP, maybe turn it into a PR and mark it as ready for review?

**Comment by brandonseydel** [comment]
Closing for new one

**Pull request closed without merging**
