### PR TITLE
Add several failing tests for attributes with multiple bindable properties

### PR DESCRIPTION
**Pull request by rluba**
# Pull Request

@fkleuver, as discussed in Discord: Aurelia doesn't handle attributes with multiple `@bindable` properties correctly.

## 📖 Description

This PR adds several tests that currently fail, but shouldn’t.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Pinging @bigopon because I believe he's got a PR open where he has addressed this or is in the process of addressing it.

**Comment by bigopon** [comment]
This should be fixed by #617

**Comment by bigopon** [comment]
@rluba we have fixed the core issue related to multiple bindings and custom attribute, but your tests will still fail because you are expecting v1 behavior of reactivity by default (without `bind` lifecycle hook, change handler will be called during initialization).

We have a RFC here for this change #670 , please chime in.

**Comment by rluba** [comment]
@bigopon Thank you. I’ve updated the tests.

**Pull request merged**
