### PR TITLE
feat(babel-jest,ts-jest): support jest v27

### LINKED ISSUE #1175: @aurelia/ts-jest and @aurelia/babel-jest need to update to support Jest v27
# 🐛 Bug Report

Our jest integration doesn't work on latest Jest v27.

## 🤔 Expected Behavior

It should work.

## 😯 Current Behavior

Jest v27 switched to ESM format.
```
> jest

TypeError: Jest: a transform must export something.
    at /Users/huocp/playground/my-app/node_modules/@jest/core/node_modules/@jest/transform/build/ScriptTransformer.js:386:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async ScriptTransformer.loadTransformers (/Users/huocp/playground/my-app/node_modules/@jest/core/node_modules/@jest/transform/build/ScriptTransformer.js:378:5)
    at async createScriptTransformer (/Users/huocp/playground/my-app/node_modules/@jest/core/node_modules/@jest/transform/build/ScriptTransformer.js:1106:3)
    at async /Users/huocp/playground/my-app/node_modules/@jest/core/build/TestScheduler.js:269:31
    at async Promise.all (index 0)
    at async TestScheduler.scheduleTests (/Users/huocp/playground/my-app/node_modules/@jest/core/build/TestScheduler.js:262:5)
    at async runJest (/Users/huocp/playground/my-app/node_modules/@jest/core/build/runJest.js:387:19)
    at async _run10000 (/Users/huocp/playground/my-app/node_modules/@jest/core/build/cli/index.js:408:7)
```
## 💁 Possible Solution

Upgrade @aurelia/ts-jest and @aurelia/babel-jest to latest Jest APIs.

## 🌍 Your Environment
Not applicable

### PR DESCRIPTION
**Pull request by 3cp**
closes #1175

### CODE REVIEW

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=a9f422dd0610ca0e71d75d46fe612fde4d1629f6&branch=jest27&commit=aa3c8f209c1f556f78309f8c853cc435f59e8efb

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=a9f422dd0610ca0e71d75d46fe612fde4d1629f6&branch=jest27&commit=4624c10d0003ce8aadfefc6911a00a25b530fc31

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=8eaae4facd7e39fb48e9c9664ec358ef93fc6454&branch=jest27&commit=d5e8dfe109785e2a0cfa3bfdad3a1c94bdfcea7b

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=8eaae4facd7e39fb48e9c9664ec358ef93fc6454&branch=jest27&commit=e3db66b79db490578f3e4d298e79a23d7b003ab7

**Comment by 3cp** [comment]
This branch has no conflict with master branch. What's this merge error in CI?

```
#!/bin/bash -eo pipefail
set -o pipefail && git merge ${CIRCLE_BRANCH} --no-ff --no-edit -Xtheirs && git status
CONFLICT (modify/delete): ****.lock deleted in jest27 and modified in HEAD. Version HEAD of ****.lock left in tree.
Auto-merging packages-cjs/ts-jest/package.json
Auto-merging packages-cjs/babel-jest/package.json
Auto-merging packages-cjs/__tests__/package.json
Automatic merge failed; fix conflicts and then commit the result.

Exited with code exit status 1
```

**Comment by 3cp** [comment]
I tried refresh package-lock and yarn.lock to solve the conflict. Then TS (v4.3.2, probably a newer version installed) complains:

```
Error: verb @aurelia/runtime build |  src/binding/ast.ts(1312,48): error TS2731: Implicit conversion of a 'symbol' to a 'string' will fail at runtime. Consider wrapping this expression in 'String(...)'.
```

This part `toStringTag.call(result)`:
```
default: throw new Error(`Cannot count ${toStringTag.call(result)}`);
```

Don't know why TS says about symbol, that toStringTag doesn't return symbol.

**Comment by bigopon** [comment]
@3cp we can probably cast it to a string. In the future, we probably will remove those 2 methods as well so its ok.

**Comment by 3cp** [comment]
There are more TS errors. Probably need to rollback typescript version.

**Comment by 3cp** [comment]
Reverted back to typescript 4.1.3.

**Comment by bigopon** [comment]
@3cp thanks. Let me handle the upgrade, probably it will have a scope bigger than expected

**Comment by 3cp** [comment]
@bigopon do you understand the playwright error?
```
error: Your local changes to the following files would be overwritten by checkout:
	****.lock
```

**Comment by bigopon** [comment]
From the lines here https://github.com/aurelia/aurelia/blob/ba81c9b5271d3a22bb9a48cbdfb481e110b53056/.circleci/config.yml#L387-L395

and the error we got, it seems somewhere in the benchmark run, changes are written to to our lock file, maybe it's the `yarn.lock` because of `lage`. We could try to add:

```diff
+ git reset --hard
  git checkout master
  master_commit=$(git rev-parse HEAD)
```
to discard the changes

**Comment by 3cp** [comment]
@bigopon can you help to push to my branch and try?

**Comment by bigopon** [comment]
@3cp Just realized the `yarn.lock` is commited. I think it' why that particular task is broken.
I've reverted the change related to the reset, and waiting to see if the guess is right. If it is, we can prevent accidental yarn lock change in the future with that, albeit not efficient.

**Comment by AureliaEffect** [comment]
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=ba81c9b5271d3a22bb9a48cbdfb481e110b53056&branch=jest27&commit=bde63892a96c671999cf8b8e5a1a76409ac9f66f

**Comment by 3cp** [comment]
@bigopon pls merge and release. After that, I will update au2 skeleton to jest v27.

**Comment by bigopon** [comment]
Awesome work, thanks @3cp

**Pull request merged**
