### PR TITLE
refactor: more linting

### PR DESCRIPTION
**Pull request by BBosman**
# Pull Request

## 📖 Description

Another round of linting. This time it's switching rules from `warning` to `errors` and fixing the resulting violations.

Highlights:
- Dropped the `eslint-plugin-security` plugin, as I was `eslint-disable`-ing all occurrences, which makes it kind of not useful.
- Switched off require `JSDoc` warnings. I do have some rules switched on that govern what JSDoc blocks should look like if they're there.
- A couple of packages had a `require()` in `src` that was not present in its `package.json` file. I Added those there.
- Removed a couple of `@ts-ignore` statements and fixed them in code. This could use some scrutiny for unintended breakage.
- And lots of small tweaks all over the map...

### 🎫 Issues

n/a

## 👩‍💻 Reviewer Notes

My suggestion would be to review it commit by commit, as I made separate commits for every rule. This allows to review them in context, instead of as one huge diff full of unrelated changes.

## 📑 Test Plan

CirclCI

## ⏭ Next Steps

More linting

### CODE REVIEW

**Comment by bigopon** [comment]
Just wanna jump in and say appreciate the PR 😙

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://30019-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://30031-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://30059-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Pull request merged**
