### PR TITLE
chore(replaceable): add failing tests for common scenarios

### PR DESCRIPTION
**Pull request by bigopon**
# Pull Request

## 📖 Description

This PR adds test cases (most are failing) for many common scenarios where `[replaceable]` is being used in conjunction with important template controllers `[repeat]`, `[with]`

### 🎫 Issues

Backward compatibility and feature completeness

## 👩‍💻 Reviewer Notes

I started to use some JSX as empty space in is hard to eliminate within the middle of template string

## 📑 Test Plan

N/A

## ⏭ Next Steps

Moar tests

@EisenbergEffect @fkleuver

### CODE REVIEW

**Comment by bigopon** [comment]
@EisenbergEffect @fkleuver this is ready

**Comment by EisenbergEffect** [comment]
@bigopon The intent with this PR is to just add the test, correct? Are these all things that vCurrent can already do? How many of them don't work in vNext?

**Comment by fkleuver** [comment]
Awesome tests, thank you <3

**Comment by bigopon** [comment]
@EisenbergEffect The combination in those test are 40% common scenario, 60% faked one, just to ensure correctness of everything. I've done pretty complex app and I've never touched anything much in that 60%

**Pull request merged**
