### PR TITLE
Code climate

### PR DESCRIPTION
**Pull request by fkleuver**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@fkleuver Something isn't quite right here. CodeClimate is reporting 2,402 issues 🤣

**Comment by fkleuver** [comment]
Yeah I noticed. Not sure what's going on, trying a few things

**Comment by fkleuver** [comment]
@EisenbergEffect I think it's just not using my changes. All my exclude patterns which are literally following the docs aren't working..

**Comment by EisenbergEffect** [comment]
Ok, let's see what happens...

**Pull request merged**
