### PR TITLE
test(e2e): properly mark failures and improve logging/reporting

### PR DESCRIPTION
**Pull request by fkleuver**
Allure and other reporting / logging stuff were still pretty rough, these a few small improvements to make the reports more useful.

### CODE REVIEW

**Comment by AureliaEffect** [comment]
Allure Report: https://2703-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/e2e/allure-report/index.html

**Comment by AureliaEffect** [comment]
Allure Report: https://2727-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/e2e/allure-report/index.html

**Comment by AureliaEffect** [comment]
Allure Report: https://2731-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/e2e/allure-report/index.html

**Comment by fkleuver** [comment]
@EisenbergEffect This can be merged. There are still too many issues with safari and edge, should probably start with running the unit tests in those browsers before trying more e2e

**Comment by bigopon** [comment]
@EisenbergEffect Now that you put those words down, I really wish to have a hall of fame, to properly name folks and their contribution, especially big effort like Fred. It's so important. And that could be a nice test for vNext app

**Comment by EisenbergEffect** [comment]
I agree. I'd like to get a better team page up for the vNext site. I also like the idea of recognizing people in a hall of fame type way for very specific contributions that have had a substantially large effect.

**Comment by fkleuver** [comment]
It's the KleuverEffect :P

**Pull request merged**
