### PR TITLE
feat(blur): blur attribute

### PR DESCRIPTION
**Pull request by bigopon**
# Pull Request

## 📖 Description

Add blur custom attribute as an official attribute resource

### 🎫 Issues

N/A

## 👩‍💻 Reviewer Notes

Timing in redundant check guard debounce behavior

## 📑 Test Plan

Cover all combination of bindables of blur custom attribute

## ⏭ Next Steps

More tests with focus/blur combined

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://23108-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://23381-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://23396-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://23543-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://23618-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://24032-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by bigopon** [comment]
@fkleuver different event will need to be handled differently, and immediately. So I couldn't figure out how to incorporate the idea of looping & checking for the manager in every frame, while maintaining efficiency.

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://24350-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Pull request merged**
