### PR TITLE
Cypress router tests doc example

### PR DESCRIPTION
**Pull request by rowellx68**
# Pull Request

## 📖 Description

This PR contains some initial Cypress tests for one of the `router`'s example application. The tests could be found inside `packages/router/test/e2e/doc-example`.

### 🎫 Issues

N/A

## 👩‍💻 Reviewer Notes

- Restore packages inside `doc-example` and `doc-example/app`.
- Run example application with `npm run watch`.
- Run cypress tests with `npm run e2e`.

## 📑 Test Plan

As per Cypress documentation, `data-test` attributes were added to elements so we can better target them for testing.

## ⏭ Next Steps

Add Cypress tests to other example applications.

### CODE REVIEW

**Comment by fkleuver** [comment]
This is awesome! Sorry for the late follow up, I've been very busy the last few days.

Is this ready to merge as far as you're concerned? I know there are some existing tests that were already failing so that's ok. They will be fixed soon. Not sure about the browserstack tests though. @BBosman do you recall if they were currently broken or not?

**Comment by BBosman** [comment]
@fkleuver I don’t remember them being broken.

**Comment by rowellx68** [comment]
@fkleuver @bbosman it should be ready pending fixing those browserstack.

Is there a better way for me to test that locally without updating the PR?

**Comment by fkleuver** [comment]
Right, I remember now. BrowserStack needs an API key which is not exposed for forked pull requests. My bad. Merging this now. Thanks a ton!!

**Pull request merged**
