### PR TITLE
Adds a TODOs Badge to the README

### LINKED ISSUE #879: Add TODOs Badge to README
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[TODOs](https://www.tickgit.com/browse?repo=github.com/aurelia/aurelia)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/aurelia/aurelia)](https://www.tickgit.com/browse?repo=github.com/aurelia/aurelia)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit` and this is not a bot posting! I'm suggesting the badge for repos that have TODO comments and already have some badges in their README.)

### PR DESCRIPTION
**Pull request by patrickdevivo**
# Pull Request

## 📖 Description

This adds a TODOs badge to the README, please see the linked issue for the full context, thank you for considering!

### 🎫 Issues

Closes #879

## 👩‍💻 Reviewer Notes

Happy to answer any questions about the service and to discuss features that may make it more useful for aurelia! Thank you for considering, feel free to close/ignore if this is not a good fit or appropriate.

## 📑 Test Plan

N/A

## ⏭ Next Steps

N/A

### CODE REVIEW

**Comment by fkleuver** [comment]
@patrickdevivo I do like the convenience of the dashboard, and having some kind of indicator for contributors to see where they might be able to chime in.

Is there any option to narrow down the badge on a per-folder/package basis?

**Comment by patrickdevivo** [comment]
@fkleuver unfortunately there's currently not a good way to narrow down the badge based on a folder or package, though that type of functionality is definitely on my `TODO` list (sorry) of features to implement: filtering/searching by folder, file pattern (extension, `_test.js`, etc), author, date, assignee `// TODO (some_username)`, etc

I don't see why the badge couldn't filter by the same parameters as well, though the functionality currently does not exist unfortunately.

**Comment by bigopon** [comment]
@fkleuver do we not need this or this cannot be merged?

**Comment by fkleuver** [comment]
@bigopon If the point is to encourage community participation by listing out what needs to be done, we'd need to organize that very differently. 98% of our TODO's probably mean nothing to people outside the core team, so I don't really see value in having a big number of TODO's listed front and center

**Pull request closed without merging**
