### PR TITLE
feat(router): add title support

### PR DESCRIPTION
**Pull request by jwx**
# Pull Request

## 📖 Description

This PR adds support for routing titles in components and routes as well as a set of title configuration options.

### 🎫 Issues

Related to https://github.com/aurelia/aurelia/issues/307, https://github.com/aurelia/aurelia/issues/369 and https://github.com/aurelia/aurelia/issues/367. 

## 👩‍💻 Reviewer Notes

Ignore everything in `packages/router/test/e2e/**` since they are just my own test applications while working.

## 📑 Test Plan

- Added new tests covering the new functionality
- Make sure existing tests pass

## ⏭ Next Steps

- Continue with triage comments
- Continue with configuration api
- Move relevant parts to `Metadata`
- Fully implement guards/hooks
- Fully implement unknown routes/components
- Add navigation events
- Make `goto` listen to navigation events instead of observing
- Fix `realworld`
- Fix proper sync/async for lifecycle hooks
- Add tests for the new `au-nav` options
- Add tests for `au-viewport-scope`
- Finish scoped viewports review
- Add tests covering scoped viewports
- Review controller parent implementation
- Review the extension points

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://48418-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://48460-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://48466-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://48596-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://48612-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by Bart76** [comment]
I just took a look at this PR.

It seems, that the `RouterConfiguration.customize` method now takes an `IRouterActivateOptions` interface instead of a `IRouterOptions` interface as its arguent. The `IRouterActivateOptions` interface is based on the `IRouterOptions` interface; it only redefines the `title` property as optional. So far so good.

But it also seems, that the `IRouterOptions` interface now defines its properties `useUrlFragmentHash`, `useHref`, `statefulHistoryLength`, `useDirectRoutes`, and `useConfiguredRoutes` as mandatory. So... when this PR will be committed and I will call `RouteConfiguration.customize` in my application code, am I then obliged to supply all five of these now mandatory properties in the config object that I supply as an argument??

**Pull request closed without merging**
