### PR TITLE
docs(watching-data): Fixed typos

### PR DESCRIPTION
**Pull request by koenbeuk**
# Pull Request

## 📖 Description
Corrected some typos on the watch decorator docs page

### CODE REVIEW

**Comment by bigopon** [comment]
@fkleuver interesting, PR can't run the e2e browser stack.

**Comment by bigopon** [comment]
@koenbeuk nice contribution 👍

**Comment by fkleuver** [comment]
> @fkleuver interesting, PR can't run the e2e browser stack.

Yeah that's OK. That's because the browserstack api key isn't exposed to external PRs for security reasons.

**Comment by fkleuver** [comment]
Thanks @koenbeuk !

**Pull request merged**
