### PR TITLE
jest transformers for babel and ts

### PR DESCRIPTION
**Pull request by 3cp**
Wrap original jest transformers to support au2 conventions.

* `@aurelia/babel-jest` to wrap `babel-jest`
* `@aurelia/ts-jest` to wrap `ts-jest`.

**Update** to clarify my approach: because jest apparently does not support chained transformers (this does not match webpack's achitect on the loader chain), I have to wrap existing `babel-jest` and `ts-jest` to apply our conventions.

### CODE REVIEW

**Comment by 3cp** [comment]
Two obstacles so far:

1. need to update typescript-eslint to support latest TypeScript syntax `import type ...`. 

```
⋊> ~/a/aurelia on jest ◦ npm ls @typescript-eslint/eslint-plugin
aurelia@ /Users/huocp/aurelia/aurelia
└── @typescript-eslint/eslint-plugin@2.16.0
```
https://github.com/typescript-eslint/typescript-eslint/pull/1697

@BBosman could we upgrade typescript-eslint to latest version 2.27.0? If there is no other complications, I can try update it in this branch too.

2. `export =` is not supported by typescript when targeting ECMAScript modules. But jest expects the transformer (a npm module) has a `Transformer`(type) object directly on `module.exports`.

This is basically the same problem I faced before when I try to write a parcel v1 plugin (it expects a commonjs module too), but gave up and decided to wait (still waiting) for parcel v2 release.

Jest support is more important than parcel. @fkleuver should we have special build setup for this two (working on the babel-jest now, no ts-jest yet) jest packages to build only commonjs dist files? This setup might be useful for some other future modules (e.g. parcel) too.

**Comment by 3cp** [comment]
@BBosman I tried to upgrade typescript-eslint 2.27.0 locally, but still see the error around `import type`. I guess I missed some other eslint packages.

**Comment by BBosman** [comment]
Did you also update typescript itself? Because this repo is still at 2.7.x as far as I know.

**Comment by 3cp** [comment]
@BBosman thx! I will try to upgrade ts from 3.7 to 3.8.

**Comment by 3cp** [comment]
I will defer the typescript upgrade to @fkleuver as I got some syntax error in `packages/runtime` with TypeScript 3.8.3.

Guess ts introduced some breaking changes again...

```
lerna ERR! npm run build exited 1 in '@aurelia/runtime'
lerna ERR! npm run build stdout:

> @aurelia/runtime@0.6.0 build /Users/huocp/aurelia/aurelia/packages/runtime
> tsc -b

src/binding/connectable.ts(65,5): error TS2322: Type 'ISubscribable & { [id: number]: number; }' is not assignable to type 'number | (ISubscribable & { [id: string]: number; })'.
  Type 'ISubscribable & { [id: number]: number; }' is not assignable to type 'ISubscribable & { [id: string]: number; }'.
    Type 'ISubscribable & { [id: number]: number; }' is not assignable to type '{ [id: string]: number; }'.
      Index signature is missing in type 'ISubscribable & { [id: number]: number; }'.
src/templating/controller.ts(237,37): error TS2345: Argument of type 'Controller<T, C>' is not assignable to parameter of type 'Controller<INode, IViewModel<INode>>'.
  Types of property 'bindingContext' are incompatible.
    Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not assignable to type 'IIndexable<IViewModel<INode> & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags...'.
      Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not assignable to type 'IIndexable<IViewModel<INode> & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags...'.
        Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not assignable to type 'IIndexable<IViewModel<INode> & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags...'.
          Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not assignable to type '{ [x: string]: unknown; [x: number]: unknown; }'.
            Index signature is missing in type '{ [K in Exclude<string, "create" | "beforeCompile" | "afterCompile" | "afterCompileChildren" | "beforeBind" | "afterBind" | "beforeUnbind" | "afterUnbind" | "beforeAttach" | "afterAttach" | "beforeDetach" | "afterDetach" | "caching" | keyof C> | Exclude<...> | Exclude<...>]: unknown; } & ICustomElementViewModel<...>...'.
src/templating/controller.ts(271,37): error TS2345: Argument of type 'Controller<T, C>' is not assignable to parameter of type 'Controller<INode, IViewModel<INode>>'.
  Types of property 'bindingContext' are incompatible.
    Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not assignable to type 'IIndexable<IViewModel<INode> & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags...'.
      Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not assignable to type 'IIndexable<IViewModel<INode> & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags...'.
        Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not assignable to type 'IIndexable<IViewModel<INode> & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags...'.
          Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not assignable to type '{ [x: string]: unknown; [x: number]: unknown; }'.
            Index signature is missing in type '{ [K in Exclude<string, "create" | "beforeCompile" | "afterCompile" | "afterCompileChildren" | "beforeBind" | "afterBind" | "beforeUnbind" | "afterUnbind" | "beforeAttach" | "afterAttach" | "beforeDetach" | "afterDetach" | "caching" | keyof C> | Exclude<...> | Exclude<...>]: unknown; } & ICustomAttributeViewModel<.....'.
src/templating/controller.ts(275,12): error TS2352: Conversion of type 'Controller<T, C>' to type 'ICustomAttributeController<T, C>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'bindingContext' are incompatible.
    Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not comparable to type 'C & { [x: string]: unknown; [x: number]: unknown; }'.
      Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not comparable to type 'C & { [x: string]: unknown; [x: number]: unknown; }'.
        Type 'IIndexable<C & { create(controller: IController<INode, IViewModel<INode>>, definition: CustomElementDefinition<Constructable<{}>>, parentContainer: IContainer, parts: Record<...> | undefined, flags: LifecycleFlags): void | PartialResourceDefinition<...>; ... 11 more ...; caching(flags: LifecycleFlags): void; }, unkn...' is not comparable to type '{ [x: string]: unknown; [x: number]: unknown; }'.
          Index signature is missing in type '{ [K in Exclude<string, "create" | "beforeCompile" | "afterCompile" | "afterCompileChildren" | "beforeBind" | "afterBind" | "beforeUnbind" | "afterUnbind" | "beforeAttach" | "afterAttach" | "beforeDetach" | "afterDetach" | "caching" | keyof C> | Exclude<...> | Exclude<...>]: unknown; } & ICustomAttributeViewModel<.....'.

```

**Comment by 3cp** [comment]
In the meantime, I will use TS 3.7 syntax (downside is moving some devDeps to deps which only introduce types).

@fkleuver no need special commonjs build for jest, I found out how to manually export needed parts.

**Comment by 3cp** [comment]
Good, `@aurelia/babel-jest` works in my local environment.
Next step is to find out how to fill up the missing unit tests for this jest transformer...

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://44758-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://44768-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://44780-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://44786-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by 3cp** [comment]
Both @aurelia/babel-jest and @aurelia/ts-jest worked as expected in local dev.

Pending implementing unit tests.

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://44825-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by 3cp** [comment]
Added unit tests. Double checked with jest skeletons aurelia/new#17 again. All good.

**Comment by 3cp** [comment]
Note the jest skeletons aurelia/new#17 use default jest jsdom env. Our au2 `*-html` core modules work well with default jest jsdom env, so the test setup file is same for jest (nodejs env) and jasmine (browser env).

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://44875-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://45061-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Pull request merged**
