### PR TITLE
fix(ui-virtualization): fix empty array edge cases

### PR DESCRIPTION
**Pull request by Lakerfield**
# Pull Request

## 📖 Description

The virtual-repeat had some problems while bound to a empty array while initializing itemHeight and minViewRequired properties. When loading data from a server, most of the time you start with an empty array. Which caused that there where no items rendered when the array was filled with data.

## 📑 Test Plan

Start with a empty array, add data after virtual-repeat is attached. Or remove all data from array and fill again.

## ⏭ Next Steps

Start publishing the @aurelia/ui-virtualization package to npm 😄

### CODE REVIEW

**Comment by bigopon** [comment]
@Lakerfield thanks for the interest, and the PR, we'll need some tests for this. I've pushed a commit that will help with the tests. You can start testing locally by running the following:
```
npm run dev -- -e ui-virtualization
```
It'll run the playwright tests at `packages/__e2e__/ui-virtualization/playwright/app.spec.ts`.
I've prepared 2 empty tests so you can start.

**Comment by Lakerfield** [comment]
Additional setup commands (for when someone is new to code base):

    npx playwright install-deps
    cd packages-tooling/vite-plugin/
    npm run build
    
Rebuild package and start test:

    npm run --prefix packages/ui-virtualization build
    npm run dev -- -e ui-virtualization -t virtual-repeat

**Comment by bigopon** [comment]
Thanks @Lakerfield , I forgot about the viteplugin since it was added recently.
You can run the following script instead:
```
npm run dev -- -d ui-virtualization -e ui-virtualization -t virtual-repeat
```
it will build `ui-virtualization` in watch mode beside the 2 other options mentioned before.
`-d`: run `dev` script
`-e`: run `e2e:watch` script
`-t`: run `test:watch` script

**Comment by Lakerfield** [comment]
@bigopon I have added a e2e test for the "Basic usage" flow. 

The playwright test.step descriptions will be shown in the ci, when the version it updated to at least 1.33.0 https://github.com/microsoft/playwright/issues/20532

**Comment by bigopon** [comment]
Thanks @Lakerfield , the reason the e2e are failing is because I'm using a different image with the one where we install deps and build. It appears cannot be reused across too different images. I'll take care of the PR, currently fixing some other bugs local.

**Comment by bigopon** [comment]
@Lakerfield this is now ready to go, I'll merge it soon.

**Pull request merged**
