### PR TITLE
fix(kernel): only propagate globally registered resources to child render contexts

### PR DESCRIPTION
**Pull request by fkleuver**
# Pull Request

## 📖 Description

Fixes https://github.com/aurelia/aurelia/issues/615 - see that issue for a description.

### 🎫 Issues

Fixes https://github.com/aurelia/aurelia/issues/615
Fixes https://github.com/aurelia/aurelia/issues/623
Needed for https://github.com/aurelia/aurelia/issues/622

## 👩‍💻 Reviewer Notes

- Shuffled a few things around in the container properties. Removed `config`. Constructor looks into its parent for what to copy, instead of `createChild` passing the info down, because no one is supposed to call the constructor directly anyway.
- Added `root` and `id` properties.
- Refactored `createRenderContext` into a class
- Added the necessary guards/logic to solve aforementioned issues

## 📑 Test Plan

There is just one big test right now that verifies the following:
- Globally registered resources are compiled+rendered anywhere in the tree
- Locally registered resources are only compiled+rendered in the declaring component, not in its children or siblings.
- Resources can still be resolved directly from the container from any level

## ⏭ Next Steps

- Might need a few more tests / edge cases specifically for the scenarios @EisenbergEffect ran into. @bigopon maybe you have some thoughts on this as well?
- Verify / integration test with https://github.com/aurelia/aurelia/issues/622

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://27988-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by EisenbergEffect** [comment]
Code looks correct based on our conversations. I'll push an integration test for the CSS modules bug.

**Comment by EisenbergEffect** [comment]
@fkleuver I pushed a simple test addition to my styles code that asserts the css modules inheritance is working as expected.

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28444-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28461-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
@EisenbergEffect What's missing is the integration with the rendering process, which is a pretty crucial moving part in the entirety of this functionality.
That test you added is useful in its own right, but could you please also add a full integration test that actually applies CSS modules somewhat in the way an end user would, and add an assertion with `getCalculatedStyle` that the correct style is applied? This full end-to-end scenario is important for preventing regressions.

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://28488-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
@EisenbergEffect I'll go ahead and merge. Could you keep that integration test as described above, as a (not very urgent but preferably within a couple weeks) todo?

**Comment by EisenbergEffect** [comment]
Definitely. Where is the best place to put it and do you have a "template" test I can use to grab the boilerplate from?

**Pull request merged**
