### PR TITLE
chore(all): add validate-commit-msg hook and commitizen script

### LINKED ISSUE #127: Add commitizen for enforcing commit message conventions

### PR DESCRIPTION
**Pull request by fkleuver**
fix #127

Commit messages are automatically validated via husky hook.
Use `npm run commit` to get an interactive CLI for building a properly formatted commit message

### CODE REVIEW

**Comment by AureliaEffect** [comment]
Allure Report: https://2671-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/e2e/allure-report/index.html

**Comment by bigopon** [comment]
@fkleuver For a PR, does this apply to only first commit (surrogate commit) or every commit needs to conform this ?

**Comment by fkleuver** [comment]
The validation will happen whenever you do `git commit` locally. You can bypass the validation with `--no-verify` for WIP commits. We could adjust the validation rules to allow those sort of special cases as well, this is just a first setup

**Comment by EisenbergEffect** [comment]
I like the idea of this :) Based on the various issues I've seen on vCurrent over the last few years, I think this will definitely help. I do worry that will be a bit much on each commit but we can play around with it a bit.

Shall we merge this?

**Comment by fkleuver** [comment]
> I do worry that will be a bit much on each commit but we can play around with it a bit

I think the `--no-verify` flag will be sufficient for WIP stuff, but in the end we do want each commit to follow some kind of convention and get ourselves in the habit of making those descriptive. The better the commit messages are, the less manual work there will be left when it comes to the change logs and writing blog post etc.

Yeah it should be good to merge.

**Pull request merged**
