### PR TITLE
WIP: router

### PR DESCRIPTION
**Pull request by fkleuver**
@EisenbergEffect @bigopon @davismj

This is just about the most quick-and-dirty implementation I could come up with to make some simple button navigation work.

### IRoute
I based the `IRoute` interface on @davismj's description in #164, so I did give some extra attention to the validation of that config. I think a more defensive approach to configuration would help users catch errors earlier and prevent them from surfacing in convoluted ways.

### RouterView
The `RouterView` class is loosely based on the `Compose` element and by no means representative of what I have in mind for it in the end. For one, it should probably be a custom attribute or a template controller, rather than a custom element. This is just step 1 to get something working. "move along people" :)

### Lifecycle hooks
I'm thinking the lifecycle/pipeline could go in the same direction as attach/detach lifecycle (with a linked list etc). The `$behavior` concept would be an interesting extensibility point for additional lifecycle hooks. Combined with some potentially custom ordering/precedence and the ability to specify which hooks to invoke via flags, this could give us more flexibility than vCurrent with at the same time a much simpler underlying mechanism.

Custom lifecycle hooks could also be registered via decorators. Multiple ways to do the same thing, really.

The way I currently implemented these is definitely not how I have it in mind for how it should be. Again, just step 1, "move along people" :)

### Resource definition
We don't want routes to conflict with the definition of custom elements. Should there be a separate resources API for routes or should they just not be resources at all?

### IRouter 
The `IRouter` interface is probably a bit more interesting. As as starting point I thought to make it a combination of the `History` and `Location` interfaces (staying as close to native api's as possible) with the addition of an API to register routes and router views. The `History` and `Location` API's are currently not much more than pass-through methods but these would get the appropriate logic eventually.

### CODE REVIEW

**Comment by davismj** [comment]
I'm going to prioritize the other specs then. I didn't think we were close to an implementation.

**Comment by AureliaEffect** [comment]
This pull request **introduces 4 alerts** when merging 481a468c07596c500fff4b73e8855e0da81813c6 into b296ed359f8c9c2f84c41e5e9e0a6b2c73927c9c - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-31d64492a5a252b0855addfec994c771011079dc)

**new alerts:**

* 4 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bigopon** [comment]
✅ 

> We don't want routes to conflict with the definition of custom elements. Should there be a separate resources API for routes or should they just not be resources at all?

Maybe the we can employ static convention and make it even simpler, since we only need to care about route definition after all?

**Comment by StrahilKazlachev** [comment]
Is there a way to determine a *route* or the *view model* of a route dynamically? Like with [`navigationStrategy`](https://aurelia.io/docs/routing/configuration#dynamically-specify-route-components) in the current router.

**Comment by fkleuver** [comment]
There will be. Just let me be absolutely clear here: this isn't even 5% of the implementation. Right now I'm personally just looking to be able to navigate between view models even if everything must be hard coded, so we can do a little more meaningful testing.

**Comment by fkleuver** [comment]
It was too early for me to open this PR, i'm closing this for now so it doesn't keep drawing attention

**Pull request closed without merging**
