### PR TITLE
feat: ability to search ancestors with IContainer.getAll()

### PR DESCRIPTION
**Pull request by bigopon**
# Pull Request

## 📖 Description

Add the ability to search the container hierarchy for a key for `.getAll()`

### 🎫 Issues

There's currently no easy way to have local syntax overriding global syntax

## 👩‍💻 Reviewer Notes

Consider the overall application of this, and the effect on perf (startup). Currently, renderer, binding command are 2 other users of `@all`.

Main changes:
- Attr parser won't allow pattern overriding: https://github.com/aurelia/aurelia/pull/819/files#diff-f862a544080f385ee659916d98eea167L26-R35
- ability to clone an attr parser: https://github.com/aurelia/aurelia/pull/819/files#diff-f862a544080f385ee659916d98eea167R53
- a bug fix in `IContainer.getAll()`: https://github.com/aurelia/aurelia/pull/819/files#diff-a60e26e3e4fd00a5f2b949a9fabd1195R930
- template compiler will check if it should clone the attribute parser based on presence of `IAttrPatterns` in the context: https://github.com/aurelia/aurelia/pull/819/files#diff-4e12e44f65fabb5da7018ededf9d5d78L116-R121

## 📑 Test Plan

N/A

## ⏭ Next Steps

N/A

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://42627-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
@bigopon I'm on board with this. Is it ready for review? I noticed some CI and possible linting errors btw

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://42785-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by bigopon** [comment]
@fkleuver it's not ready for review, as I haven't been able to settle on this scenario:
```
Parent (a, b, c for KeyA)
  Child (d for KeyA)
```
What would we yield with `getAll(KeyA, true)`?
- a b c d
- d a b c

**Comment by bigopon** [comment]
Btw, unless we yield 2 dim array, we won't be able to figure out which comes from what container when from the result, maybe it's not important, but for order sensitive consumers of `.getAll()`, it's quite difficult. For example: any syntax registered first will shadow everything else after it

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://42915-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://43091-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://43114-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://43132-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by bigopon** [comment]
@fkleuver ready for review, I've updated the PR description as well. Please have a look

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://43715-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by bigopon** [comment]
superseded by another PR. Layered attr patterns will be incorporated by #988

**Pull request closed without merging**
