### PR TITLE
docs(validation): applied click-to-load to demos

### PR DESCRIPTION
**Pull request by Sayan751**
# Pull Request

### CODE REVIEW

**Comment by bigopon** [comment]
@Sayan751 man you are so consistent ❤️

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://46346-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by Sayan751** [comment]
@bigopon Someone (I) had to do it :)

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://46371-121594173-gh.circle-artifacts.com/0/test/js-framework-benchmark/webdriver-ts-results/table.html

**Pull request merged**
