### PR TITLE
examples

### PR DESCRIPTION
**Pull request by fkleuver**
Removed e2e tests and deps, and target the published `dev` versions, so that they're actually examples and not multifunctional kitchen sinks for our testing purposes :)

Also added an example with `iife` and inline script tags. Working quite nicely!

### CODE REVIEW

**Comment by AureliaEffect** [comment]
This pull request **introduces 2 alerts** and **fixes 2** when merging 13ef948b3e8a5d0d6269f47813af973d6b338d30 into 76c783cd8920a4eccd944023b82aea2a89a2e494 - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-66a7a07a41f8b5fe429239f8f8a069826a783ebe)

**new alerts:**

* 2 for Superfluous trailing arguments

**fixed alerts:**

* 2 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AureliaEffect** [comment]
Allure Report: https://2869-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/e2e/allure-report/index.html

**Comment by bigopon** [comment]
Very nice. Later when we have one single bundle for all core packages, 3 script tags will merge into one and also can be fetched from a cdn, then it's 👌 ❤️ 

Thanks @fkleuver !

**Comment by fkleuver** [comment]
Might as well. Single file has arrived :p @bigopon

**Comment by AureliaEffect** [comment]
This pull request **introduces 2 alerts** and **fixes 2** when merging dd5170648f18638370e781ff416defc984acf651 into 76c783cd8920a4eccd944023b82aea2a89a2e494 - [view on LGTM.com](https://lgtm.com/projects/g/aurelia/aurelia/rev/pr-8664ef552326604d7f134e180c9b97fea6528b33)

**new alerts:**

* 2 for Superfluous trailing arguments

**fixed alerts:**

* 2 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by bigopon** [comment]
💯
Rollup is nice, isn't it 😉

**Comment by AureliaEffect** [comment]
Allure Report: https://2874-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/e2e/allure-report/index.html

**Comment by fkleuver** [comment]
Yep. Goes to show how a couple bad experiences can seriously drive you away from something even if for a bad reason. But with both you, jods and 1-2 others keep talking about it I had to reconsider. I'm glad that I did
🎢

**Pull request merged**
