### PR TITLE
test(realworld): add conventions and new router features

### PR DESCRIPTION
**Pull request by jwx**
# Pull Request

## 📖 Description

This PR makes realworld use conventions and new router features.

It follows https://github.com/aurelia/aurelia/pull/571.

## 👩‍💻 Reviewer Notes

There's a behaviour in router that currently creates a bug in realworld when looking at certain article details. It'll be changed/fixed shortly.

## 📑 Test Plan

- Eventually add e2e tests?

## ⏭ Next Steps

- Update router and/or realworld to remove the bug

### CODE REVIEW

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://24097-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by EisenbergEffect** [comment]
Should we remove the `inject` decorators as well and let TS contructor metadata handle this?

**Comment by AureliaEffect** [comment]
JS Framework Benchmark: https://24328-121594173-gh.circle-artifacts.com/0/home/circleci/repo/test/js-framework-benchmark/webdriver-ts-results/table.html

**Comment by fkleuver** [comment]
Let's use the `@IParam` parameter decorators for interfaces. Easier to maintain than `@inject` decorator or the static property

**Comment by jwx** [comment]
Can we do the `@IParam/@inject` thing in a different PR so that this can be merged?

**Comment by jwx** [comment]
(We'll come back to `realworld` at least once anyway to fix the `@dependencies`.)

**Pull request merged**
