### PR TITLE
chore(all): --save is removed for npm install

### PR DESCRIPTION
**Pull request by 3cp**
Also cleanup --save-dev to shorter -D. Fixed few wrong install commands, for example webpack-loader should be a dev dep.

### CODE REVIEW

**Comment by fkleuver** [comment]
If we're going the shortcut route why not abbreviate `install` to `i` as well? I always type `npm i -D something`, `npm i --save something`, `npm i -g something`, etc

**Comment by 3cp** [comment]
Yes, why not.

**Comment by 3cp** [comment]
I don't understand the failure on unit_test_node. Something wrong with current master head?

**Comment by fkleuver** [comment]
@3cp Looks to me like it's all working. `js_framework_benchmark` is just broken atm for unrelated reasons. Is this ready to merge?

**Comment by 3cp** [comment]
Yes. Ready for me. But have a look first, no much changed.

**Comment by fkleuver** [comment]
Haha that's a ton of completely unrelated changes in various build scripts too :P
Can't do any harm though I guess. It works universally. So I'll merge. Thanks!

**Pull request merged**
